DEM_COL_NAMES = ['2016 Q4 median home val',
 '2020 Q1 median home val',
 'crimes per sq mile',
 'predicted crime rate per 1000 ppl',
 'crime ratio - trend vs present',
 'crime ratio - present vs projected',
 'property crime rate',
 'property crime ratio - trend vs present',
 'property crime ratio - present vs projected',
 'employment change',
 'population change',
 'mobile home pct',
 'change in rent prices',
 'seasonal home pct',
 'rent pct',
 'homeonwer pct',
 'homeownership change',
 'new home pct',
 'dorms pct',
 'vacant homes pct',
 'small apt pct',
 'large apt pct',
 '% rural',
 '% remote',
 'education score',
 'vacancy changes',
 '% commute times under 30-45 min',
 '% commute times under 45-60 min',
 '% commute times under 60-90 min',
 'unemployment % change',
 'in college %',
 'work from home pct',
 'per capita income',
 'median household income',
 'income change',
 'median household income change',
 'unemployment pct']
